### ISSUE TITLE
can your code work with python 2.7?

### ISSUE THREAD

**Issue by kaishijeng** [dvornikita/blitznet#10]
I have python 2.7 and got the following error when I ran:
python test.py --run_name=BlitzNet300_VOC07+12 --dataset=voc07 --split=test --image_size=300 --detect --segment --ckpt=1

Traceback (most recent call last):
  File "test.py", line 111, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test.py", line 46, in main
    loader = VOCLoader('07', 'test')
  File "/mnt/2TB/src/blitznet/voc_loader.py", line 22, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)

Thanks,

**Comment by fastlater** [comment]
In the README says you need Python 3.5.
The code did run in my computer without problems using python 3.5.4.
You can have a both python versions installed on the computer. Then you will be able to run a script with a specific version according to your needs.

**Comment by dvornikita** [comment]
It was designed using python 3.5 so we don't ensure compatibility with python 2.x. Regarding the error message you have, you can delete the line that causes the error - it's an artifact from an earlier version (thanks for pointing out) - and it will not affect the code. There might be some other issues with division and dictionary merging. You can inspect the code to fix this manually or install python 3.5, as @fastlater suggests, which is a better solution.
