### ISSUE TITLE
Filter class

### ISSUE THREAD

**Issue by bhack** [dvornikita/blitznet#11]
Do you think that we could add to the detector a list class indexs to filter?
I think like something that could be used in https://github.com/dvornikita/blitznet/blob/master/detector.py#L122 and put in Detector class constructor.

What do you think?

**Comment by dvornikita** [comment]
We can, yes. But what is the purpose?

**Comment by bhack** [comment]
Generally in the demo you can have some false positive on minor/marginal objects so could be useful to filter on the category that are mainly present in that context if you know it.

**Comment by dvornikita** [comment]
@bhack sounds reasonable.
