### ISSUE TITLE
real-time problem

### ISSUE THREAD

**Issue by C-ID** [dvornikita/blitznet#19]
hello
     I'v runned the script demo.py  (I turned off draw option when call detector.feed_forward) using your pre-trained model BlitzNet300_COCO+VOC07+12 on our GPU Tesla P100. but I found that only 12 fps when feed 300x200 pictures to the model. Your article "BlitzNet: A Real-Time Deep Network for Scene Understanding", However, shows that It can reach 24 fps on GPU Titan X.  Actually, the performance of Tesla P100(4.7 ~ 5.3 TFLOPS) is better than Titan X(up to 0.355 TFLOPS), Why?

**Comment by dvornikita** [comment]
Run the code for benchmark, please. It's benchmark.py. For more details refer to #7
