### ISSUE TITLE
run train voc2012 error.

### ISSUE THREAD

**Issue by Frostinassiky** [dvornikita/blitznet#2]
Hello.
When I trained the blitznet using resnet50, I met the followed error information:
```
Traceback (most recent call last):
  File "training.py", line 323, in <module>
    tf.app.run()
  File "/home/xum/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "training.py", line 293, in main
    dataset = get_dataset('voc12-' + args.split)
  File "/home/xum/github/blitznet/datasets.py", line 144, in get_dataset
    num_samples=sum(splits_to_sizes[s] for s in files),
  File "/home/xum/github/blitznet/datasets.py", line 144, in <genexpr>
    num_samples=sum(splits_to_sizes[s] for s in files),
KeyError: 'voc12-train'
```
Then I checked the dataset file folder. 
```
$ ls -l
total 3185444
-rw-r--r-- 1 xum g-xum        375 Aug 29 14:44 go.sh
-rw------- 1 xum g-xum    5387494 Aug 29 15:32 nohup.out
-rw-r--r-- 1 xum g-xum  166310709 Aug 30 11:31 voc12-train-segmentation
-rw-r--r-- 1 xum g-xum  166660879 Aug 30 11:32 voc12-val-segmentation
drwxr-xr-x 4 xum g-xum       4096 Nov  6  2007 VOCdevkit
-rw-r--r-- 1 xum g-xum  451020800 Nov  6  2007 VOCtest_06-Nov-2007.tar
-rw-r--r-- 1 xum g-xum  460032000 Nov  6  2007 VOCtrainval_06-Nov-2007.tar
-rw-r--r-- 1 xum g-xum 1999639040 May 11  2012 VOCtrainval_11-May-2012.tar
```
Both **voc12-train-segmentation** and **voc12-val-segmentation** should be produced by *datasets.py*, but why errors?

Here is my training command
```
python training.py --run_name=BlitzNet300_x4_VOC0712_detseg --dataset=voc12 --trunk=resnet50 --x4 --detect --segment
```

**Comment by dvornikita** [comment]
There is a problem on my side. In the last commit, I pushed the modification affecting the files training.py and paths.py that fixes this issue. So either git-clone the project again or check the modifications by inspecting the commit.

To train on a particular split of voc12 please specify the flag --dataset=voc12-splitname, where splitname is in [train, val, trainval].
Training on voc07 operates on both train and val splits by default and is called with a flag --dataset=voc07.
Now it should be fine.

Thank you for noticing.
