### ISSUE TITLE
Speed of BlitzNet 

### ISSUE THREAD

**Issue by fujihuang** [dvornikita/blitznet#21]
I have a new paper which intend to submit to ICME 2018 (the DDL is tomorrow, 12.15), when I cited your paper in my paper, I got one question about the speed in your paper: when the input is 300x300, the speed of yours is much lower than the corresponding SSD, however when the input is 512x512, yours is better than the corresponding SSD which uses VGGNet as base net, it is amazing, can you explain some details? Or since the BlitzNet is realized with TensorFlow, which will be faster than official SSD ? Or else...
  I will be very grateful for your reply to shihua@stumail.neu.edu.cn. (I could not find your email.... I am so sorry for such hurry)

**Comment by fujihuang** [comment]
Hi,
  Thank you very much for your reply. I am so sorry that I can not reply you with email since encountering such error: 554 Your access to this mail system has been rejected due to the sending MTA's poor reputation. If you believe that this failure is in error, please contact the intended recipient via alternate means.. 
  And we have got your point, it is very helpful for us.  Thanks again for your great work on BlitzNet, it is amazing~~
Best regards,
Shihua Huang

**Comment by dvornikita** [comment]
@fujihuang No worries. It's all fine. Thanks for a good question and good luck with your paper.
