### ISSUE TITLE
ShapeError when trying to run demo.py with BlitzNet300_COCO

### ISSUE THREAD

**Issue by deeptf** [dvornikita/blitznet#24]
I am attempting to run the demo.py without any change to the code, by downloading the COCO model and I get a shape error as following: 

InvalidArgumentError : Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,512,64]
	 [[Node: save/Assign_266 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ssd/Conv/weights, save/RestoreV2_266)]]

Any help please ?

**Comment by dvornikita** [comment]
The demo is limited to the VOC categories. You need to run a model that was trained with VOC or finetuned on it.

**Comment by deeptf** [comment]
Thanks @dvornikita for the clarification. Even for VOC only trained model, I am ending up with a dataloss error as mentioned on another issue.

**Comment by dvornikita** [comment]
Closing due to lack of recent activity.

**Comment by ryohachiuma** [comment]
Hi, I met the same problem, and I change the VOC_CATS in demo.py to 81 coco categories.
But I get the same error.  
When I run 
```
python demo.py --run_name=BlitzNet300_COCO --image_size=300 --detect --segment --eval_min_conf=0.5 --ckpt=1
```
, I get shape mis-match error below.
```
Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,512,64]
```

When I add --seg_filter_size=3 option, I get the error.
```
Assign requires shapes of both tensors to match. lhs shape= [81] rhs shape= [64]
```
That means, BlitzNet300_COCO model only takes 64 categories?

Thank you.

**Comment by EchoAmor** [comment]
Hello ! I met the same problem, I want to use BlitzNet300_COCO model,how should I do to run the demo please?Have u solve this problem now? Thanks a lot! @dvornikita @kemangjaka

**Comment by dvornikita** [comment]
As I mentioned above, the demo is not meant to work with COCO categories and models trained on COCO. You can either follow the readme and run it with VOC categories, or you will need to modify the code in case you still want to run it with COCO
