### ISSUE TITLE
Ways to improve on coarse segmentation

### ISSUE THREAD

**Issue by revilokeb** [dvornikita/blitznet#26]
In my experiments on various datasets I am getting fairly coarse semantic segmentation results (with 512), even if running on 512x512 images. They are often similar to what can be seen for the Cityscapes segmentation example in https://github.com/dvornikita/blitznet/issues/15.

I have run trainings with and without --x4, results do not seem to be dramatically better for segmentation with stride 4 in the last layer.

Is that something others can confirm? If so what could be a good way to improve on it (possibly at the expense of somewhat reduced FPS)?

**Comment by dvornikita** [comment]
Hi,
I agree that there is not so much difference in the sharpness of masks between x512 and x300 models. What you can try to do is to increase the capacity of the segmentation branch by adding more channels to layers, or maybe treat the finest-scale layer in a different way than the others. I haven't tried that but it sounds reasonable to me.
You also can always improve the sharpness by using CRF on top of the neural net output with some drop in FPS.

**Comment by revilokeb** [comment]
@dvornikita ok many thanks for your ideas. I will update this when I am getting improved results, for now I am closing.
