### ISSUE TITLE
VOC12 segmentation image resized

### ISSUE THREAD

**Issue by aokic1** [dvornikita/blitznet#35]
![image](https://user-images.githubusercontent.com/10206799/42462031-643d8956-83a2-11e8-9407-0b4aaab94a8e.png)

As shown on the image the width and height dimension sizes are exchanged for segmentation.
We used VOC12 train and segmentation split dataset for training and VOC12 val and segmentation split dataset for test. Image size is default(300).

**Comment by dvornikita** [comment]
I see the problem. Apparently, this happened in the last pull-request. I'll fix it.
Thanks for noticing.

**Comment by dvornikita** [comment]
@aokic1, Should work now. Reopen if you encounter weird behavior.
