### ISSUE TITLE
Problem with running a demo with pretrained net

### ISSUE THREAD

**Issue by lukaszkepka** [dvornikita/blitznet#38]
Hi, 

I have encountered a problem during running demo with pretrained models. Console output: 

NotFoundError (see above for traceback): Key ssd/confidence/ssd_back/block_rev1/biases not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Have anyone had similar issue?

**Comment by lukaszkepka** [comment]
I am running demo.py with parameters:
--run_name=BlitzNet512_COCO+VOC07+12 --x4 --detect --segment --eval_min_conf=0.5 --ckpt=1

**Comment by dvornikita** [comment]
If you are running a model BlitzNet512... you need to specify the flag --image_size=512 and remove the flag --x4, as stated in the documentation.

**Comment by lukaszkepka** [comment]
Indeed, it worked. Thank you!
