### ISSUE TITLE
python training.py --run_name=BlitzNet300_x4_VOC0712_detseg --dataset=voc07+12-segmentation --trunk=resnet50 --x4 --batch_size=32 --optimizer=adam --detect --segment --max_iterations=65000 --lr_decay 40000 50000

### ISSUE THREAD

**Issue by chenbolinstudent** [dvornikita/blitznet#44]
tensorflow.python.framework.errors_impl.NotFoundError: /home/cbl/PycharmProjects/blitznet-master/Datasets/voc07-trainval-segmentation; No such file or directory

how to solve it?,thanks

**Comment by dvornikita** [comment]
The way to solve all the issues that arise in your experiments is just to follow the preparation step by step!
