### ISSUE TITLE
ModuleNotFoundError: No module named 'progressbar'

### ISSUE THREAD

**Issue by chenbolinstudent** [dvornikita/blitznet#46]
when I run
python test.py --run_name=BlitzNet300_x4_VOC0712_detseg --dataset=voc07 --split=test --image_size=300 --x4 --detect --segment --ckpt=65 --save_first_n=100
I meet :ModuleNotFoundError: No module named 'progressbar'
I have install progressbar and with python3.6
could you help me?

**Comment by dvornikita** [comment]
check that you are using the python where progressbar is installed, in case you have multiple virtual environments.
