### ISSUE TITLE
About the arguments in class feed_forward

### ISSUE THREAD

**Issue by Sung-Bin-Kim** [dvornikita/blitznet#49]
This network is perfect.
While using this network, i have some questions about some arguments in demo.py. In line 62 and 63 in demo.py
detector.feed_forward(img=image, name=name, w=w, h=h, draw=True,
seg_gt=None, gt_bboxes=None, gt_cats=None)
i don't get what seg_gt, gt_bboxes, gt_cats means. Could you explicitly explain to me about what these argument means and how it works? Thankyou

**Comment by dvornikita** [comment]
Hi,
Those are the ground truth boxes, segmentation and object categories used in model evaluation on a test set. Since in demo we have only images without corresponding ground truth annotations, they are passed as None.
Thanks for reposting :)
