### ISSUE TITLE
Test on MS COCO dataset based on trained checkpoint

### ISSUE THREAD

**Issue by Hwang64** [dvornikita/blitznet#52]
After I download the trained checkpoint on COCO dataset, after test, the AP are all 0, the command is 
python test.py --run_name=BlitzeNet300_x4_coco_det --dateset=coco --split=val2017 --x4 --image_size=300 --detect --ckpt=1
so I don't know what is the problem, looking forward for your help~~~

**Comment by dvornikita** [comment]
I can't tell you exactly why you have 0 ap since there is not enough details. However, one thing I  noticed is that you use a split 'val2017' that wasn't in a list of allowed splits initially. Check that you adapted everything correctly.

**Comment by Hwang64** [comment]
Thank you for you reply~
I use the coco 2017 val set to evaluate the detection performance and I have modified the corresponding codes to test the model. However, when I use the released model with the command above, all the results are 0. I only modify the code related to the pre-preparation of the dataset and any other codes are the same with the original. So I am confused that if there are configurations or anything else I don't set well. There is another interesting thing is that when I evaluate the release model on Pascal voc 2007, the results are corret~~
so i am confused now and need for your help~~~~

**Comment by dvornikita** [comment]
As I said already, 'val2017' is not in the list of supported splits since we have used splits of 2014 year. The corresponding split to 'val2017' is 'minival2014'. So in your command put "--split=minival2014' instead.
Be sure you have the splits downloaded and all the paths (to the dataset and splits) set up correctly.
