### ISSUE TITLE
How to calculate each class of IoU？

### ISSUE THREAD

**Issue by pengjizhi** [dvornikita/blitznet#55]
Hello author! Thank you for your hard work.
I have some questions about the calculation of per class IoU.

The final result is the mIoU, how can I get the IoU of each class?

**Comment by dvornikita** [comment]
Hello,

We use a standard metric, provided by tensorflow api, that automatically computes mean IoU. I believe, to compute per-class IoU, without changing the code to much, you may want to access the confusion matrix, which is a local variable withing the created mean_iou tensorflow op, and than use it to compute IoU per class manually, as TP / (TP + FP + FN), where TP is True Positives, FP is False Positives and FN is False Negatives.

**Comment by pengjizhi** [comment]
@dvornikita 
thank you! Author.
I finally copied the tensorflow source code, returned the local variable of the confusion matrix, got the confusion matrix, and got the per-class IoU.
I also want to ask a question, does the miou you mentioned in the paper contain the background class in it?
By reading your code, it is found that the returned miou is calculated for each class, but the background class is also calculated into it.
For the VOC dataset, this will result in a higher miou value, since most of one image are black pixels（background class）. So I think the value of miou should not contain the background class?

**Comment by dvornikita** [comment]
I believe you are right. I will make corresponding modifications to the code and push it soon. However, as for the results reported in the paper, we did not compute the mIoU using our code. Instead, we uploaded the masks to the test server and it computed the mIoU according to their protocol (which doesn't take into account the background class).

**Comment by pengjizhi** [comment]
Thank you for your answer, this question can be closed.
