### ISSUE TITLE
About MIoU result

### ISSUE THREAD

**Issue by QTJiebin** [dvornikita/blitznet#56]
Hi, I want to compare with your BlitzNet512_COCO_VOC07+12, but I can not find the MIoU result on PASCAL VOC 2012 in your published ICCV2017. So, is it convenient for you to tell me the MIoU result. Thx.

**Comment by dvornikita** [comment]
Hi,

Here are the results for [BlitzNet512](http://host.robots.ox.ac.uk:8080/eval/view_submission/12221/) and [BlitzNet300](http://host.robots.ox.ac.uk:8080/eval/view_submission/12222/) from the Pascal VOC 2012 evaluation server.

Best,
Nikita
