### ISSUE TITLE
Demo code

### ISSUE THREAD

**Issue by bhack** [dvornikita/blitznet#8]
Seems that all the API requires always the GT cause also the test code works with datasets.
Do you have a minimal demo code to just visually evaluate results on new images from internet?

**Comment by fastlater** [comment]
@bhack  you can check the loader.py and set it to load the images from a different folder or load a single image.

**Comment by dvornikita** [comment]
Thanks, @fastlater. It's true that you can modify the loader and also turn off evaluation. But ideally, it should be easier than that.
I guess @bhack has the point there. I probably should provide some demo code to work with arbitrary images. I'm gonna make it and let you know when I push it.

**Comment by fastlater** [comment]
@dvornikita We will be happy to see a clean demo code from you in the future. Just for testing, I created a new loader and used the functions from detector.py. It was a little bit dirty the code but at least, I got the desired output.

**Comment by dvornikita** [comment]
@bhack, @fastlater, @AlonTetro, the demo has arrived.
Be careful, there are some minor changes in detector.py, so check them if you don't want to pull the new version.

**Comment by bhack** [comment]
Thank you. Is the demo working with BlitzNet512?

**Comment by fastlater** [comment]
@dvornikita  Thank you for letting me know. I will take a look on it.

**Comment by dvornikita** [comment]
@bhack it does. The only difference with testing is that you don't have a dataset linked to the loader. Just specify the right flags for running the demo as you would do for testing. 
The only limitation for now is Pascal VOC categories. I'll push the COCO labels later.

**Comment by bhack** [comment]
@dvornikita I've asked cause with BlitzNet512 I got `tensorflow.python.framework.errors_impl.NotFoundError: Key ssd_back/block_rev6/shortcut/weights not found in checkpoint`

**Comment by bhack** [comment]
@dvornikita Results seems goods. I've noted generally that MSCOCO And PASCAL GT segmentation masks are not so precise. Have you tried to add also [Davis dataset masks](https://github.com/fperazzi/davis) to the training mix?

**Comment by dvornikita** [comment]
@bhack No we didn't. The strength of the method is to discover some hidden correlations in bounding boxes and segmentation annotations to reduce class confusion for both and make localization of boxes more precise, while still being realtime. I guess the Davis dataset has only segmentations and if you want them more accurate it would make more sense to use a state-of-the art segmentation method. 
But we may make good use of this dataset in the future. Thanks.

**Comment by bhack** [comment]
@dvornikita Yes I understand the original scope. But I still think that Blitznet segmentation quality is quite good. I think is not a problem to derive a bounding box from a segmentation Mask like in the [Mscoco API official toolkit](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/mask.py#L99).

**Comment by dvornikita** [comment]
@bhack I looked closer at the Davis and I agree with you, it's feasible. For sure it can be used at least as a solid pretraining.

**Comment by bhack** [comment]
@dvornikita The insteresting thing is to evaluate how the quality of the mask influence the segmentation performance of your model. So probably one of the first interesting approach is just to finetune on Davis the models that you have already pretrained.
