### ISSUE TITLE
Problem when trying to test on your pretrain model 

### ISSUE THREAD

**Issue by AlonTetro** [dvornikita/blitznet#9]
Hi dvornikita, 

First of all thanks for this amazing work! :) 
I have some problems when I trying to test the pretrain BlitzNet512 model.

The following message appears and I don't know how to deal with it.. maybe you have some solution for me :)

"InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3,3,512,64] rhs shape= [1,1,512,64]"

**Comment by dvornikita** [comment]
can you please send the command you are running?

**Comment by AlonTetro** [comment]
Sure :) Thanks for the quick response!ץ 

python test.py --run_name=BlitzNet512_COCO+VOC07+12 --dataset=voc07 --split=test --image_size=512 --detect --segment --ckpt=1

Without the --segment flag everything works well

**Comment by dvornikita** [comment]
Try to specify the flag --seg_filter_size=3.
I guess I have slightly different architectures for different datasets so the default configurations don't always work. Need to re-upload the right ones.

**Comment by AlonTetro** [comment]
Works great! Thank you :)
